Business page optimization and file folder structure
abubakar-sazim/Restaurant-Frontend pull request #2
Opened 2024-02-27 18:16 UTC by abubakar-sazim

2024-02-27 19:59 UTC, jUddinSazim requested changes

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/app/restaurants/[business_id]/page.tsx
if we rename the directory from `business_id` to `businessId` we can update in like 7 for this file

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/app/restaurants/[business_id]/page.tsx
> +    business_id: string;
update the dir name, so we can do 
```suggestion
    businessId: string;
```

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/DetailPage/Attributes/Attributes.tsx
> +  return (
this render looks pretty manual, we can do it dynamically also.
lets put it as least priority for refactoring. If we can complete all the other things, we will refactor it at last

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/DetailPage/Attributes/index.ts
> +export * from './Attributes'
new line to end

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/DetailPage/Attributes/IconLoader.tsx
this file looks to be a helper file for Attributes.tsx, so rename it to `Attributes.helper.ts`

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/DetailPage/Attributes/IconLoader.tsx
also remember, a `tsx` file is a react component file or hook file

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/DetailPage/HeaderSection.tsx
put HeaderSection in a Self contained directory

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/DetailPage/Reviews/Reviews.tsx
> +        <HighlightedReview
instead of making two component, HighlightedReview and and AllReviewes =>

make on `ReviewCard` component,
the card component should accept a prop e.g `highlight={true}`
so if highlight is true, render highlight class, or just render normal class.

then in Reviews component, map through the reviews like: 

```
restaurantReviews.map((review) => <Reviews review={review} highlight={somecondition})

```

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/Helper/processFunctions.ts
this is just a helper functions, so should not be inside /components dir, move it out somewhere like `/utils/textHelpers.ts`

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/HomePage/HomePage.tsx
> +          <RestaurantSkeleton />
DRY! do not repeat! make it dynamic

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/HomePage/RestaurantCard.tsx
> +  const generateRandomImage = () => {
move this to some helper file

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/HomePage/RestaurantCard.tsx
move in to individual directory

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/HomePage/RestaurantList.tsx
move in to individual directory

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/HomePage/RestaurnatSkeleton.tsx
move in to individual directory

2024-02-27 19:59 UTC, jUddinSazim commented on dishdive/components/HomePage/homePage.constants.ts
rename `HomePage.constants.ts`

2024-02-28 06:09 UTC, abubakar-sazim commented on dishdive/components/DetailPage/Attributes/IconLoader.tsx
bhai ts files throws error for icons

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/app/page.tsx
>      </div>
just return ``<HomePage />`` from here, this divs are useless anyway

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/app/globals.css
> +}
newline

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/components/DetailPage/HeaderSection/index.ts
> +export * from "./HeaderSection";
newline

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/components/DetailPage/LocationSection/index.ts
> +export * from "./LocationSection";
newline

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/components/DetailPage/Reviews/ReviewCard.tsx
> +  const business_id = params.business_id;
```suggestion
  const businessId = params.businessId;
```

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/components/DetailPage/Reviews/ReviewCard.tsx
> +    business_id: string;
```suggestion
    businessId: string;
```

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/components/DetailPage/Reviews/ReviewCard.tsx
> +          </div>
dont you think this portion of code is same as line 52:55 ? so instead to repeating, lets make component like ``<FakeReviewer />``

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/components/DetailPage/Reviews/Reviews.tsx
> +          }}
looks like we are passing an object containing only one prop. lets do it like 
```suggestion
          bussinessId={businessId}
```

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/components/HomePage/HomePage.tsx
> +          {loading && (
why we are checking loading twice?

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/components/HomePage/RestaurantList/index.ts
> +export * from "./RestaurantList";
newline

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/components/HomePage/RestaurantSkeleton/index.ts
> +export * from "./RestaurantSkeleton";
newline

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/components/HomePage/Restaurantcard/index.ts
> +export * from "./RestaurantCard";
newline

2024-02-28 08:55 UTC, jUddinSazim commented on dishdive/components/HomePage/index.ts
> +export * from './HomePage'
newline

2024-02-29 08:50 UTC, jUddinSazim approved these changes

2024-02-29 09:18 UTC, merged